version: '3.8'

services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: .
    volumes:
      - .:/app    # Монтируем текущую директорию в /app внутри контейнера
      - /app/node_modules  # Исключаем node_modules из монтирования
    networks:
      - backend
    command: sh -c "bun run prisma:generate && bun run prisma:deploy && bun run start"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
